# MI Ch0

## Linear Algebra

In [1]:
import numpy as np

In [36]:
A = np.array([
    [1,2,3],
    [4,3,2],
    [2,-2,-1]
])

B = np.array([
    [-1,2,3],
    [2,-3,2],
    [0,3,2]
])

C = np.array([
    [1,2,3],
    [2,3,4],
    [3,6,9]
])

### Product

In [3]:
np.dot(A,B)

array([[ 3,  5, 13],
       [ 2,  5, 22],
       [-6,  7,  0]])

### Transpose

In [4]:
A.T

array([[ 1,  4,  2],
       [ 2,  3, -2],
       [ 3,  2, -1]])

$(AB)^T=B^TA^T$

In [15]:
np.dot(A,B).T

array([[ 3,  2, -6],
       [ 5,  5,  7],
       [13, 22,  0]])

In [16]:
np.dot(B.T,A.T)

array([[ 3,  2, -6],
       [ 5,  5,  7],
       [13, 22,  0]])

### inverse of a square matrix

$A^{-1}A=AA^{-1}=I$

In [13]:
np.dot(A,np.linalg.inv(A)) 

array([[ 1.00000000e+00,  8.32667268e-17,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  5.55111512e-17],
       [-1.11022302e-16,  8.32667268e-17,  1.00000000e+00]])

In [14]:
np.dot(np.linalg.inv(A),A)

array([[1.00000000e+00, 5.55111512e-17, 2.77555756e-17],
       [0.00000000e+00, 1.00000000e+00, 5.55111512e-17],
       [0.00000000e+00, 1.11022302e-16, 1.00000000e+00]])

$(AB)^{-1}=B^{-1}A^{-1}$

In [17]:
np.linalg.inv(np.dot(A,B))

array([[ 0.28      , -0.16545455, -0.08181818],
       [ 0.24      , -0.14181818,  0.07272727],
       [-0.08      ,  0.09272727, -0.00909091]])

In [18]:
np.dot(np.linalg.inv(B),np.linalg.inv(A))

array([[ 0.28      , -0.16545455, -0.08181818],
       [ 0.24      , -0.14181818,  0.07272727],
       [-0.08      ,  0.09272727, -0.00909091]])

$(A^T)^{-1} = (A^{-1})^T$

In [19]:
np.linalg.inv(A.T)

array([[-0.04, -0.32,  0.56],
       [ 0.16,  0.28, -0.24],
       [ 0.2 , -0.4 ,  0.2 ]])

In [20]:
np.linalg.inv(A).T

array([[-0.04, -0.32,  0.56],
       [ 0.16,  0.28, -0.24],
       [ 0.2 , -0.4 ,  0.2 ]])

### Rank

In [39]:
np.linalg.matrix_rank(A)

3

### Trace
Tr(AB) = Tr(BA)

In [24]:
np.trace(A)

3

In [25]:
np.trace(B)

-2

In [26]:
np.trace(np.dot(A,B))

8

In [27]:
np.trace(np.dot(B,A))

8

### Determinant
det(AB)=det(A)det(B),
det(A)=det(A^T),$det(A^{-1})=\frac{1}{det(A)}$

In [30]:
np.linalg.det(A)

-25.000000000000007

In [37]:
np.linalg.det(C)

0.0

### Eigenvalues
$Ax=\lambda x -> (A-\lambda I)x=0$, $det(A)=\prod{\lambda}$, $Tr(A)=\sum{\lambda}$

In [46]:
a,b = np.linalg.eig(A)
a,b

(array([-3.11309058,  4.20191178,  1.91117881]),
 array([[-0.63262421,  0.37389924, -0.04444013],
        [ 0.16649445,  0.90473508, -0.83740542],
        [ 0.75635059, -0.2040926 ,  0.54477265]]))

In [47]:
np.linalg.det(A)

-25.000000000000007

In [51]:
np.prod(a)

-24.999999999999982

In [52]:
np.trace(A)

3

In [53]:
np.sum(a)

2.9999999999999982

## Optimization

### Newton
$x_{n+1}=x_n-\frac{f^{'}(Jacobian)}{f^{''}(Hessian)}$

### Gradient Desent

$x_{n+1}=x_n-0.1f^{'}$